# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
cache: packages
sudo: false
warnings_are_errors: false

install:
    - Rscript -e 'install.packages(c("devtools", "XML"))'

#env
env:
  global:

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

#before_script
before_script:

#after_success
after_success:

# Custom parts:

#r_github_packages
r_github_packages:

#r_packages
r_packages:

#services
services:

#before_install
before_install:
